### ISSUE TITLE
Update Color Scheme

### ISSUE THREAD

**Issue by thilo** [berlincoworking/coworkingfestival.github.io#51]
in branch `vers-2020` update the color scheme to a light blue.

e.g. 
<img width="87" alt="Screenshot 2020-09-01 at 11 03 12" src="https://user-images.githubusercontent.com/8471/91830206-c8423400-ec42-11ea-9bd1-6facf5a5c5c3.png">

**Comment by Kriesse** [comment]
work in progress

![image](https://user-images.githubusercontent.com/53684/92044406-77375a80-ed7e-11ea-9310-b468588c3788.png)
