### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by thilo** [berlincoworking/coworkingfestival.github.io#52]
A new Logo for Website/Twitter/FB/Instagram

Twitter Banner: 1500 x 500 px
Twitter Avatar: 400 x 400 px
FB Avatar 360 x 360 px
FB Banner: 820 x 462 px

**Comment by Kriesse** [comment]
![fb-avatar](https://user-images.githubusercontent.com/53684/92259253-6f3efe00-eed7-11ea-8889-4264b390c512.png)
![fb-banner](https://user-images.githubusercontent.com/53684/92259262-6fd79480-eed7-11ea-80b1-8c599e2ae726.png)
![fb-cover](https://user-images.githubusercontent.com/53684/92259273-70702b00-eed7-11ea-8c35-b137a39fe38e.png)
![googleform-header](https://user-images.githubusercontent.com/53684/92259282-70702b00-eed7-11ea-8eed-4cd7b97a5097.png)
![instagram-avatar-600x600](https://user-images.githubusercontent.com/53684/92259288-7108c180-eed7-11ea-8b3b-d2dd31ebe2a7.png)
![instagram-avatar](https://user-images.githubusercontent.com/53684/92259296-71a15800-eed7-11ea-9f6f-75a935b1a127.png)
![twitter-avatar](https://user-images.githubusercontent.com/53684/92259299-71a15800-eed7-11ea-8156-2272621c4632.png)
![twitter-cover](https://user-images.githubusercontent.com/53684/92259304-71a15800-eed7-11ea-87f7-b1ff1c5c7eb6.png)
