### ISSUE TITLE
Create a splash page with the new colors and date

### ISSUE THREAD

**Issue by thilo** [berlincoworking/coworkingfestival.github.io#53]
Have a splash page up with the new colors and the new date
14.-18. Sept 2020

**Comment by Kriesse** [comment]
Update:

![image](https://user-images.githubusercontent.com/53684/92043894-515d8600-ed7d-11ea-9079-052073ff8066.png)
![image](https://user-images.githubusercontent.com/53684/92043914-5de1de80-ed7d-11ea-8d07-8904705ba0d8.png)

**Comment by Kriesse** [comment]
Some details still to do, e.g. colors on events page (if we still need this page?)
