### ISSUE TITLE
Update "Register Your Space Now" 

### ISSUE THREAD

**Issue by Kriesse** [berlincoworking/coworkingfestival.github.io#54]
Should this stay?
![image](https://user-images.githubusercontent.com/53684/92035368-e6a54e00-ed6e-11ea-9b1d-708b7070957f.png)

If yes: 
the [linked google doc](https://docs.google.com/forms/d/e/1FAIpQLSfNZHS9kH_oKND9YOHX2P1qlM-3P2jJHxYX4wN0SLRGdafFTg/closedform
) needs updating:

![image](https://user-images.githubusercontent.com/53684/92035402-f45ad380-ed6e-11ea-8d14-bb7915fcc182.png)

**Comment by thilo** [comment]
Updated already, thank you!
