### ISSUE TITLE
Update landing page copy

### ISSUE THREAD

**Issue by MoreMaddy** [berlincoworking/coworkingfestival.github.io#56]
_The current copy has a typo and sub-optimal grammar. Here is an update:_ 

The Pandemic was a challenge for all of us. The festival will be back in September 2022. If you need a break from the home office or your company office feels too crowded, find a space in your neighborhood.

```
The Pandemic was a challenge for all of us. The festival will be back in September 2022. If you need a break from the home office or your company office feels too crowded, find a space in your neighborhood.
```

**Comment by thilo** [comment]
thank you, fixed.
