### ISSUE TITLE
A new Logo for Website 2022

### ISSUE THREAD

**Issue by thilo** [berlincoworking/coworkingfestival.github.io#57]
A new Logo for Website/Twitter/FB/Instagram

Twitter Banner: 1500 x 500 px
Twitter Avatar: 400 x 400 px
FB Avatar 360 x 360 px
FB Banner: 820 x 462 px

See #52 for reference

**Comment by Kriesse** [comment]
## FB Banner
![fb-banner](https://user-images.githubusercontent.com/53684/179035114-e9eb8fa1-6399-47f8-a2ba-5a191f614517.png)

## FB Avatar
![fb-avatar](https://user-images.githubusercontent.com/53684/179035105-c155d848-0394-4887-b2b3-f384382b0fe9.png)

## FB Cover
![fb-cover](https://user-images.githubusercontent.com/53684/179035098-2276094f-1950-430a-81e2-dd8344eac9d1.png)

## Twitter Cover
![twitter-cover](https://user-images.githubusercontent.com/53684/179035103-57a18043-dad5-4c2c-8939-0b1408c9e291.png)

## Twitter Avatar
![twitter-avatar](https://user-images.githubusercontent.com/53684/179035106-ab8b68d8-5bcd-4091-9752-7c875d63b8bb.png)

## IG Avatar
![instagram-avatar-600x600](https://user-images.githubusercontent.com/53684/179035089-065ad72a-a966-4a9b-bbee-c88a07e4625c.png)

## Googleform Header
![googleform-header](https://user-images.githubusercontent.com/53684/179035110-bafa7ca9-da90-47c7-a4cf-57a3b5fed75b.png)

**Comment by Kriesse** [comment]
done, closing
