### ISSUE TITLE
Create social media and press assets for 2023

### ISSUE THREAD

**Issue by Kriesse** [berlincoworking/coworkingfestival.github.io#73]
Create new press and social media assets for 2023.

- [ ] Twitter Banner: 1500 x 500 px
- [ ] Twitter Avatar: 400 x 400 px
- [ ] FB Avatar 360 x 360 px
- [ ] FB Banner: 820 x 462 px
- [ ] Linkedin?
- [ ] press kit?

**Comment by Kriesse** [comment]
@thilo Can you confirm the assets' dimensions above? (I copied them from last year).

Also need to know what's needed for Linkedin, press kit, and anything else I didn't list.

**Comment by thilo** [comment]
@Kriesse press kit time for later. Linked in I take some of the existing formats.

**Comment by Kriesse** [comment]
@thilo FYI, all the assets. Already uploaded them to FB and Linkedin (don't have access / can't get it to work in IG and Twitter)


![instagram-avatar](https://github.com/berlincoworking/coworkingfestival.github.io/assets/53684/787bff52-753b-4a71-a4e0-62570c889db7)
![fb-avatar](https://github.com/berlincoworking/coworkingfestival.github.io/assets/53684/4d1a21c6-454d-4485-8caa-840e2833880d)

![twitter-avatar](https://github.com/berlincoworking/coworkingfestival.github.io/assets/53684/87d38d48-fdac-4fa6-800f-cf52763f5f60)

![fb-cover](https://github.com/berlincoworking/coworkingfestival.github.io/assets/53684/438f9edd-5c06-4da8-8a35-20277130cec4)
![linkedin-cover](https://github.com/berlincoworking/coworkingfestival.github.io/assets/53684/3a46991e-b719-482f-98a3-00accc902788)
![fb-banner](https://github.com/berlincoworking/coworkingfestival.github.io/assets/53684/d8aaa4dc-660a-4784-84a1-
![instagram-avatar-600x600](https://github.com/berlincoworking/coworkingfestival.github.io/assets/53684/7851d7f0-3053-45cb-9087-353fba0f137b)
![twitter-cover](https://github.com/berlincoworking/coworkingfestival.github.io/assets/53684/604f5318-f816-43f3-b238-130356da3928)
035cacb7a97f)
![googleform-header](https://github.com/berlincoworking/coworkingfestival.github.io/assets/53684/72f7e6f4-9fa7-4a41-b352-87cf5ca6ba34)
